title: CMDLP
description: A lightweight, easy-to-use C++ library for parsing command-line options.
author: Enrico Fraccaroli
show_downloads: false
google_analytics:
theme: jekyll-theme-leap-day
social:
  email: enrico.fraccaroli@univr.it
